services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: postgresql://hrms_user:JJQEwB2IdkrH4zKcx1uXxzdAo2k704Xe@dpg-d6et7mp5pdvs73f0vs0g-a/hrms_lite_zn6f
    autoDeploy: true
